version: '2'

services:
  php:
    build: ./.devops/php-fpm
    volumes:
      - ./:/var/www/app
    ports:
      - "9000:9000"

  db:
    image: mysql
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    links:
      - php

  nginx:
    image: nginx:alpine
    volumes:
      - ./.devops/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./.devops/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./:/var/www/app
    ports:
      - "1234:80"
    links:
      - php
      - db