version: '3'

services:
  php:
    build: ./.devops/php-fpm
    volumes:
      - ./:/var/www/app
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./.devops/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./.devops/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/app
    ports:
      - "1234:80"
    links:
      - php