version: '3'
services:
  api:
    build:
      context: .
    volumes:
      - ./:/app

  composer:
    image: exchange-composer:0.1.0
    build:
      context: ./composer
    command: composer install
    volumes:
      - ./:/app
