version: "3.7"
services:
  personare-api:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: ./docker/Dockerfile.fpm
    image: samirortiz/personare
    container_name: personare-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - personare-api
  nginx:
    image: nginx:1.17-alpine
    container_name: personare-nginx-app
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - personare-api
networks:
  personare-api:
    driver: bridge