name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  back-end:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install
      run: composer install

    - name: Lint
      run: composer lint

    - name: Static Analysis Code
      run: composer static-analysis

    - name: Unit test
      run: composer test
